server.port: 9903

spring:
  config:
    use-legacy-processing: true
  application.name: read-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: sajad
    password: myjava123
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
  cloud.config:
    discovery:
      enabled: true
      serviceId: config-server
    fail-fast: true
    retry:
      initialInterval: 2000
      maxAttempts: 30
  mvc.servlet.load-on-startup: 1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

